api:
  base_url: "https://test.svw.info:8080"  # Now HTTPS
  timeout: "30s"
  ssl:
    verify: true                      # Verify server certificates
    ca_file: ""                       # Custom CA bundle (optional)
    client_cert: ""                   # Client certificate (optional - mTLS)
    client_key: ""                    # Client private key (optional - mTLS)
    insecure_skip_verify: false       # Never skip in production

mcp:
  port: 3000
  mode: "both"
  http_port: 8888
  ssl:
    enabled: false                     # SSL required when true
    cert_file: "certs/server.crt"     # Server certificate
    key_file: "certs/server.key"      # Server private key
    ca_file: ""                       # CA for client cert verification (optional)
    min_version: "1.2"                # Minimum TLS version
    max_version: "1.3"                # Maximum TLS version
    cipher_suites: []                 # Empty = use Go defaults (secure)
    require_client_cert: false        # mTLS optional
    hsts_max_age: 31536000           # HSTS 1 year
    auto_redirect_http: false         # Don't redirect HTTP to HTTPS
    auto_generate_certs: true         # Fallback to self-signed
    auto_cert_hosts: ["localhost", "127.0.0.1"] # Hosts for auto-generated certs

logging:
  level: "info"
  format: "json"
  
  # Console output configuration
  console:
    enabled: true
    force_colors: false
    
  # File output configuration
  file:
    enabled: true
    base_path: "logs"
    
  # Log rotation configuration
  rotation:
    max_size: 100          # MB - rotate when file reaches this size
    max_age: 1             # days - rotate daily
    max_backups: 30        # number of rotated files to keep
    compress: true         # compress rotated files
    compress_after: 1      # days - compress files older than this
    
  # Log separation configuration
  separation:
    enabled: true          # Enable log separation
    access_log: true       # Separate access logs
    error_log: true        # Separate error logs
    metrics_log: true      # Separate metrics logs
    
  # Async logging configuration
  async:
    enabled: true          # Enable async logging
    buffer_size: 1000      # Buffer size for async writes
    flush_interval: "5s"   # Force flush interval
    shutdown_timeout: "10s" # Graceful shutdown timeout
    
  # Metrics configuration
  metrics:
    enabled: true          # Enable performance metrics
    include_caller: true   # Include file:line in logs
    include_request_id: true # Include request IDs
    include_duration: true # Include request duration

# Environment-specific overrides
development:
  mcp:
    ssl:
      enabled: false                  # Disabled in development
      auto_generate_certs: true       # But ready to enable
  api:
    ssl:
      insecure_skip_verify: true      # Allow self-signed in dev
